# Generated by Django 6.0.1 on 2026-01-12 18:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('PIN', 'PIN Entry'), ('QR', 'QR Code'), ('NFC', 'NFC Card'), ('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face Recognition')], db_index=True, max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Method',
                'verbose_name_plural': 'Attendance Methods',
                'db_table': 'api_attendancemethod',
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='api.attendancemethod'),
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.admin')),
            ],
            options={
                'verbose_name': 'Class Session',
                'verbose_name_plural': 'Class Sessions',
                'db_table': 'api_classsession',
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('success', models.BooleanField(default=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('device_info', models.TextField(blank=True, null=True)),
                ('class_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='api.class')),
                ('student_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='api.student')),
                ('method_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='api.attendancemethod')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='api.classsession')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'db_table': 'api_attendancelog',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NFCCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nfc_card', to='api.student')),
            ],
            options={
                'verbose_name': 'NFC Card',
                'verbose_name_plural': 'NFC Cards',
                'db_table': 'api_nfccard',
            },
        ),
        migrations.CreateModel(
            name='StudentPIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_hash', models.CharField(max_length=255)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_set', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pin', to='api.student')),
            ],
            options={
                'verbose_name': 'Student PIN',
                'verbose_name_plural': 'Student PINs',
                'db_table': 'api_studentpin',
            },
        ),
        migrations.CreateModel(
            name='ClassAttendanceMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_methods', to='api.class')),
                ('method_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_methods', to='api.attendancemethod')),
            ],
            options={
                'verbose_name': 'Class Attendance Method',
                'verbose_name_plural': 'Class Attendance Methods',
                'db_table': 'api_classattendancemethod',
                'indexes': [models.Index(fields=['class_id', 'method_id'], name='class_method_idx')],
                'unique_together': {('class_id', 'method_id')},
            },
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['class_id', 'is_active'], name='session_class_active_idx'),
        ),
        migrations.AddIndex(
            model_name='classsession',
            index=models.Index(fields=['expires_at'], name='session_expires_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['student_id', 'timestamp'], name='log_student_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['class_id', 'timestamp'], name='log_class_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['method_id', 'timestamp'], name='log_method_time_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancelog',
            index=models.Index(fields=['success', 'timestamp'], name='log_success_time_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['card_uid'], name='nfc_card_uid_idx'),
        ),
        migrations.AddIndex(
            model_name='nfccard',
            index=models.Index(fields=['student_id'], name='nfc_student_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpin',
            index=models.Index(fields=['student_id'], name='student_pin_idx'),
        ),
        migrations.AddIndex(
            model_name='studentpin',
            index=models.Index(fields=['locked_until'], name='pin_locked_idx'),
        ),
    ]
